app:
    resource: '@AppBundle/Controller/'
    type: annotation

wise_api:
    resource: "@AppBundle/Controller/"
    type:     rest
    prefix:   /api

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
